version: "3.3"
services:
  server1:
    image: "http-server"
    container_name : server-1
    ports:
      - "8089:8081"
    volumes:
      - ./server1.log:/home/app/server.log:z
  server2:
    image: "http-server"
    container_name : server-2
    ports:
      - "8090:8081"
    volumes:
      - ./server2.log:/home/app/server.log:z
