apiVersion: v1
kind: ConfigMap
metadata:
  name: server-configmap
  namespace : {{ .Values.deployment.namespace }}
  labels:
    app: {{ .Values.deployment.namespace }}
data:
 server-name: {{ .Values.appServer.name}}
