apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
  namespace: astral
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Mi
  storageClassName: custom
